site_name: DiSky Wiki
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: simple/discord
  palette:
    scheme: slate
    primary: orange
    accent: amber
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.footer
    - content.code.copy
repo_url: https://github.com/DiSkyOrg/DiSky

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2020 - 2024 ItsTheSky
extra_css:
  - stylesheets/main.css

extra:
  status:
    new: 'Recently added'
    deprecated: 'Deprecated'
  social:
    - icon: simple/discord
      link: https://disky.me/discord
    - icon: simple/github
      link: https://github.com/DiSkyOrg/DiSky
    - icon: material/cloud
      link: https://itsthesky.net/

plugins:
  - search
  - include_dir_to_nav
  - macros:
      include_dir: macros
      j2_block_start_string: "[[[%"
      j2_block_end_string: "%]]]"
      j2_variable_start_string: "[[["
      j2_variable_end_string: "]]]"

nav:
  - 'Wiki':
      - 'Home': home.md
      - 'Getting Started':
          - 'Asking Help': getting-started/asking-help.md
          - 'Installation': getting-started/0-installation.md
          - 'Bot Creation': getting-started/1-bot-creation.md
          - 'Bot Loading': getting-started/2-bot-loading.md
          - 'F.A.Q.': getting-started/faq.md
      - 'Bot':
          - 'Cache Policy & Flags': bot/policy.md
          - 'Presence & Status': bot/presence-and-status.md
          - 'Gateway Intents': bot/intents.md
          - 'Multiple Bots': bot/multiple-bots.md
          - 'Application': bot/bot-application-info.md
      - 'Messages':
            - 'Simple Messages': messages/simple-messages.md
            - 'Advanced Messages': messages/advanced-messages.md
            - 'Emojis': messages/emojis.md
            - 'Message Wrapper': messages/message-wrapper.md
            - 'Webhooks': messages/webhooks.md
            - 'Polls': messages/polls.md
            - 'Discord Commands': messages/discord-commands.md
      - 'Guild':
          - 'Automod': guild/automod.md
          - 'Logs': guild/logs-manipulation.md
          - 'Forums': guild/forums.md
          - 'Welcome Screen': guild/guild-welcome-screen.md
      - 'Interactions':
            - 'Components': interactions/components.md
            - 'Slash Structure': interactions/slash-structure.md
            - 'Slash Commands': interactions/slash-commands.md
            - 'Modals': interactions/modals.md
            - 'Select Menus': interactions/selectmenu-dropdown.md
  - 'Modules': modules
  - 'Documentation':
      - 'Types': docs/types.md
      - 'Effects': docs/effects.md
      - 'Events': docs/events.md
      - 'Expressions': docs/expressions.md
      - 'Conditions': docs/conditions.md
      - 'Sections': docs/sections.md
      - 'Modules':
          - 'LavaPlayer': docs/lavaplayer.md
          - 'TranSkript': docs/transkript.md
  - 'SkImage2': skimage
  - 'BooSK':
      - 'Getting Started': boosk/getting-started.md
      - 'Create a Book': boosk/create-a-book.md